# Generated by Django 5.0.1 on 2024-03-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onderzoek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('startdatum', models.DateField()),
                ('einddatum', models.DateField()),
                ('criteria', models.TextField()),
                ('beschrijving', models.TextField()),
            ],
        ),
    ]
