# Generated by Django 5.0.1 on 2024-03-10 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_onderzoek_accounts_onderzoek'),
    ]

    operations = [
        migrations.DeleteModel(
            name='accounts_onderzoek',
        ),
    ]
