# Generated by Django 5.0.1 on 2024-03-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_ervaringsdeskundige_type_onderzoek'),
    ]

    operations = [
        migrations.AddField(
            model_name='ervaringsdeskundige',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
