# Generated by Django 5.0.1 on 2024-03-06 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_ervaringsdeskundige_is_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisatie',
            name='beschrijving',
            field=models.TextField(blank=True, default='Geen beschrijving beschikbaar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisatie',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='organisatie',
            name='website',
            field=models.CharField(default='Geen beschrijving beschikbaar', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Bericht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onderwerp', models.CharField(max_length=255)),
                ('bericht', models.TextField()),
                ('verzenddatum', models.DateTimeField(auto_now_add=True)),
                ('gelezen', models.BooleanField(default=False)),
                ('afzender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verzonden_berichten', to=settings.AUTH_USER_MODEL)),
                ('ontvanger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ontvangen_berichten', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
