# Generated by Django 5.0.1 on 2024-03-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_ervaringsdeskundige_bijzonderheden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onderzoek',
            name='doelgroep_beperking',
            field=models.ManyToManyField(choices=[('Doof', 'Doof'), ('Slechthorend', 'Slechthorend'), ('Doofblind', 'Doofblind (Auditief)'), ('Blind', 'Blind'), ('Slechtziend', 'Slechtziend'), ('Kleurenblind', 'Kleurenblind'), ('DoofblindVisueel', 'Doofblind (Visueel)'), ('Amputatie en mismaaktheid', 'Amputatie en mismaaktheid'), ('Artritus', 'Artritus'), ('Fibromyalgie', 'Fibromyalgie'), ('Reuma', 'Reuma'), ('Verminderde handvaardigheid', 'Verminderde handvaardigheid'), ('Spierdystrofie', 'Spierdystrofie'), ('RSI', 'RSI'), ('Tremor en Spasmen', 'Tremor en Spasmen'), ('Quadriplegie of tetraplegie', 'Quadriplegie of tetraplegie'), ('ADHD', 'ADHD'), ('Autisme', 'Autisme'), ('Leerstoornis', 'Leerstoornis'), ('Geheugen beperking', 'Geheugen beperking'), ('Multiple Sclerose', 'Multiple Sclerose'), ('Epilepsie', 'Epilepsie'), ('Migraine', 'Migraine')], to='accounts.beperking'),
        ),
    ]
