# Generated by Django 5.0.1 on 2024-03-09 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_onderzoek_doelgroep_beperking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onderzoek',
            name='doelgroep_beperking',
        ),
    ]
