# Generated by Django 5.0.1 on 2024-03-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_accounts_onderzoek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts_onderzoek',
            name='titel',
            field=models.CharField(max_length=255),
        ),
    ]
