# Generated by Django 5.0.1 on 2024-03-10 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_accounts_onderzoek_titel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts_onderzoek',
            old_name='einddatum',
            new_name='datum_tot',
        ),
        migrations.RenameField(
            model_name='accounts_onderzoek',
            old_name='startdatum',
            new_name='datum_vanaf',
        ),
        migrations.RemoveField(
            model_name='accounts_onderzoek',
            name='criteria',
        ),
        migrations.AddField(
            model_name='accounts_onderzoek',
            name='beloning',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='accounts_onderzoek',
            name='leeftijd_tot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accounts_onderzoek',
            name='leeftijd_van',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accounts_onderzoek',
            name='status',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounts_onderzoek',
            name='type_onderzoek',
            field=models.CharField(default=10, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accounts_onderzoek',
            name='beschrijving',
            field=models.CharField(max_length=255),
        ),
    ]
