# Generated by Django 5.0.1 on 2024-03-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_einddatum_accounts_onderzoek_datum_tot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onderzoek',
            name='doelgroep_beperking',
            field=models.ManyToManyField(to='accounts.beperking'),
        ),
        migrations.AlterField(
            model_name='ervaringsdeskundige',
            name='beperkingen',
            field=models.ManyToManyField(blank=True, to='accounts.beperking'),
        ),
        migrations.AlterField(
            model_name='onderzoek',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
