# Generated by Django 5.0.1 on 2024-03-11 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_onderzoek_doelgroep_beperking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onderzoek',
            name='doelgroep_beperking',
        ),
    ]
