# Generated by Django 5.0.1 on 2024-03-18 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_onderzoek'),
        ('accounts', '0013_remove_onderzoek_doelgroep_beperking'),
    ]

    operations = [
    ]
