# Generated by Django 5.0.1 on 2024-03-13 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_merge_20240314_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onderzoek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('nieuw', 'Nieuw'), ('goedgekeurd', 'Goedgekeurd'), ('afgekeurd', 'Afgekeurd'), ('gesloten', 'Gesloten')], default='nieuw', max_length=50)),
                ('is_beschikbaar', models.BooleanField(default=True)),
                ('beschrijving', models.TextField()),
                ('datum_vanaf', models.DateField()),
                ('datum_tot', models.DateField()),
                ('type_onderzoek', models.CharField(choices=[('op_locatie', 'Op locatie'), ('telefonisch', 'Telefonisch'), ('online', 'Online')], max_length=50)),
                ('locatie', models.CharField(blank=True, max_length=255, null=True)),
                ('met_beloning', models.BooleanField(default=False)),
                ('beloning', models.TextField(blank=True, null=True)),
                ('doelgroep_leeftijd_van', models.IntegerField()),
                ('doelgroep_leeftijd_tot', models.IntegerField()),
            ],
        ),
    ]
