# Generated by Django 5.0.1 on 2024-03-17 21:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_onderzoek'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organisatie',
            name='api_key',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organisatie',
            name='gebruiker',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisatie', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organisatie',
            name='type',
            field=models.CharField(choices=[('commercieel', 'Commercieel'), ('non_profit', 'Non-profit')], max_length=50),
        ),
    ]
