# Generated by Django 5.0.1 on 2024-04-04 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_merge_20240318_1313'),
        ('accounts', '0016_organisatie_api_key_organisatie_gebruiker_and_more'),
    ]

    operations = [
    ]
