# Generated by Django 5.0.1 on 2024-04-04 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_merge_20240404_1800'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ervaringsdeskundige',
            name='beperkingen',
        ),
        migrations.AddField(
            model_name='onderzoek',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organisatie',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Deelname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_deelname', models.DateTimeField(auto_now_add=True)),
                ('gebruiker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('onderzoek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.onderzoek')),
            ],
        ),
        migrations.DeleteModel(
            name='Beperking',
        ),
        migrations.AddField(
            model_name='ervaringsdeskundige',
            name='beperkingen',
            field=models.CharField(blank=True, choices=[('Geen Beperking', 'Geen Beperking'), ('Doof', 'Doof'), ('Slechthorend', 'Slechthorend'), ('Doofblind (Auditief)', 'Doofblind (Auditief)'), ('Blind', 'Blind'), ('Slechtziend', 'Slechtziend'), ('Kleurenblind', 'Kleurenblind'), ('DoofblindVisueel', 'Doofblind (Visueel)'), ('Amputatie en mismaaktheid', 'Amputatie en mismaaktheid'), ('Artritus', 'Artritus'), ('Fibromyalgie', 'Fibromyalgie'), ('Reuma', 'Reuma'), ('Verminderde handvaardigheid', 'Verminderde handvaardigheid'), ('Spierdystrofie', 'Spierdystrofie'), ('RSI', 'RSI'), ('Tremor en Spasmen', 'Tremor en Spasmen'), ('Quadriplegie of tetraplegie', 'Quadriplegie of tetraplegie'), ('ADHD', 'ADHD'), ('Autisme', 'Autisme'), ('Leerstoornis', 'Leerstoornis'), ('Geheugen beperking', 'Geheugen beperking'), ('Multiple Sclerose', 'Multiple Sclerose'), ('Epilepsie', 'Epilepsie'), ('Migraine', 'Migraine')], default='Geen Beperking', max_length=100),
        ),
    ]
