# Generated by Django 5.0.1 on 2024-03-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onderzoek_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onderzoek',
            name='beschrijving',
            field=models.CharField(default='Standaard beschrijving', max_length=100),
        ),
    ]
